[project]
name = "python-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coverage>=7.8.0",
    "faker>=37.1.0",
    "ipdb>=0.13.13",
    "pytest>=8.3.5",
    "requests>=2.32.3",
]
